### ISSUE TITLE
Move Site Extension to nuget.org

### ISSUE THREAD

**Issue by davidebbo** [puneet-gupta/EventViewerAzure#4]
Please see https://github.com/Azure/app-service-announcements/issues/87 for detailed announcement.

**Important**: if your site extension is still relevant, you need to do this before June 1st 2018. Please let me know if you have any questions.

Thanks!

**Comment by puneetg1983** [comment]
Hi @davidebbo, this extension has a few bugs and is not actively maintained because this was integrated into support tools in Diagnose and Solve blade so I am ok to deprecate it at this time.

**Comment by davidebbo** [comment]
Makes sense. How about unlisting it now from siteextensions.net?

**Comment by puneetg1983** [comment]
done @davidebbo

**Comment by davidebbo** [comment]
Looks like only the latest was unlisted. I just unlisted the rest.
